name: Renovate
on:
  schedule:
    # runs the first Sunday of each month at midnight UTC
    - cron: '0 0 1-7 * 0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.5
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
