name: Renovate
on:
  push:
    branches:
      - renovate
  pull_request:
    branches:
      - renovate
  schedule:
    # every week at 00:00 on Sunday
    - cron: '0 0 * * 0'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ github.repository }}